In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
from __future__ import division
import math
from datetime import datetime

In [2]:
ign = pd.read_csv ("ign.csv")
del ign['Unnamed: 0']
ign.head()

,score_phrase,title,url,platform,score,genre,editors_choice,release_year,release_month,release_day
0,Amazing,LittleBigPlanet PS Vita,/games/littlebigplanet-vita/vita-98907,PlayStation Vita,9.0,Platformer,Y,2012,9,12
1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,/games/littlebigplanet-ps-vita-marvel-super-he...,PlayStation Vita,9.0,Platformer,Y,2012,9,12
2,Great,Splice: Tree of Life,/games/splice/ipad-141070,iPad,8.5,Puzzle,N,2012,9,12
3,Great,NHL 13,/games/nhl-13/xbox-360-128182,Xbox 360,8.5,Sports,N,2012,9,11
4,Great,NHL 13,/games/nhl-13/ps3-128181,PlayStation 3,8.5,Sports,N,2012,9,11

In [3]:
salesdec = pd.read_csv ("Video_Games_Sales_as_at_22_Dec_2016.csv")
salesdec.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ign.rename(columns={'title':'Name', 'platform':'Platform'}, inplace=True)
#ign.rename(columns={'platform':'Platform'}, inplace=True)

In [5]:
#s1 = pd.merge(ign, salesdec, left_on=['genre','platform'], right_on=['Genre','Platform'])

In [6]:
#s1[['Genre','genre']]

In [7]:
ign.head()

,score_phrase,Name,url,Platform,score,genre,editors_choice,release_year,release_month,release_day
0,Amazing,LittleBigPlanet PS Vita,/games/littlebigplanet-vita/vita-98907,PlayStation Vita,9.0,Platformer,Y,2012,9,12
1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,/games/littlebigplanet-ps-vita-marvel-super-he...,PlayStation Vita,9.0,Platformer,Y,2012,9,12
2,Great,Splice: Tree of Life,/games/splice/ipad-141070,iPad,8.5,Puzzle,N,2012,9,12
3,Great,NHL 13,/games/nhl-13/xbox-360-128182,Xbox 360,8.5,Sports,N,2012,9,11
4,Great,NHL 13,/games/nhl-13/ps3-128181,PlayStation 3,8.5,Sports,N,2012,9,11

In [8]:
salesdec.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#df['period'] = df[['Year', 'quarter']].apply(lambda x: ''.join(x), axis=1)
#dataframe["period"] = dataframe["Year"].map(str) + dataframe["quarter"]
#datetime.datetime.strptime(string_date, "%Y-%m-%d %H:%M:%S.%f")

In [10]:
ign['Release_Date'] = ign['release_year'].map(str) +'-' + ign['release_month'].map(str) + '-' +ign['release_day'].map(str)

ign['Release_Date'] = pd.to_datetime(ign['Release_Date']) #creating new column with timeseries oh YEAR:MONTH:DATE

ign.Release_Date[0]

Timestamp('2012-09-12 00:00:00')

In [11]:
ign.head()

,score_phrase,Name,url,Platform,score,genre,editors_choice,release_year,release_month,release_day,Release_Date
0,Amazing,LittleBigPlanet PS Vita,/games/littlebigplanet-vita/vita-98907,PlayStation Vita,9.0,Platformer,Y,2012,9,12,2012-09-12
1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,/games/littlebigplanet-ps-vita-marvel-super-he...,PlayStation Vita,9.0,Platformer,Y,2012,9,12,2012-09-12
2,Great,Splice: Tree of Life,/games/splice/ipad-141070,iPad,8.5,Puzzle,N,2012,9,12,2012-09-12
3,Great,NHL 13,/games/nhl-13/xbox-360-128182,Xbox 360,8.5,Sports,N,2012,9,11,2012-09-11
4,Great,NHL 13,/games/nhl-13/ps3-128181,PlayStation 3,8.5,Sports,N,2012,9,11,2012-09-11

In [12]:
x = pd.merge(ign, salesdec, on=['Name','Platform'], suffixes=['_ign','_vg'], how='outer', indicator=True)
x.head()

,score_phrase,Name,url,Platform,score,genre,editors_choice,release_year,release_month,release_day,...,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,_merge
0,Amazing,LittleBigPlanet PS Vita,/games/littlebigplanet-vita/vita-98907,PlayStation Vita,9.0,Platformer,Y,2012.0,9.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,/games/littlebigplanet-ps-vita-marvel-super-he...,PlayStation Vita,9.0,Platformer,Y,2012.0,9.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,Great,Splice: Tree of Life,/games/splice/ipad-141070,iPad,8.5,Puzzle,N,2012.0,9.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,Great,NHL 13,/games/nhl-13/xbox-360-128182,Xbox 360,8.5,Sports,N,2012.0,9.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,Great,NHL 13,/games/nhl-13/ps3-128181,PlayStation 3,8.5,Sports,N,2012.0,9.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [13]:
b = x[x.Name == 'Grand Theft Auto V']
b[['Name', 'Platform','Global_Sales','_merge']]

                     Name       Platform  Global_Sales      _merge
17163  Grand Theft Auto V  PlayStation 3           NaN   left_only
17164  Grand Theft Auto V       Xbox 360           NaN   left_only
17998  Grand Theft Auto V  PlayStation 4           NaN   left_only
17999  Grand Theft Auto V       Xbox One           NaN   left_only
18067  Grand Theft Auto V             PC          1.17        both
18635  Grand Theft Auto V            PS3         21.04  right_only
18642  Grand Theft Auto V           X360         16.27  right_only
18660  Grand Theft Auto V            PS4         12.61  right_only
18770  Grand Theft Auto V           XOne          5.48  right_only

In [14]:
#checking for all possible values for platform names

In [15]:
ign['Platform'].value_counts()

PC                      3370
PlayStation 2           1686
Xbox 360                1631
Wii                     1366
PlayStation 3           1356
Nintendo DS             1045
PlayStation              952
Wireless                 910
iPhone                   842
Xbox                     821
PlayStation Portable     633
Game Boy Advance         623
GameCube                 509
Game Boy Color           356
Nintendo 64              302
Dreamcast                286
PlayStation 4            277
Nintendo DSi             254
Nintendo 3DS             225
Xbox One                 208
PlayStation Vita         155
Wii U                    114
iPad                      99
Lynx                      82
Macintosh                 81
Genesis                   58
NES                       49
TurboGrafx-16             40
Android                   39
Super NES                 33
NeoGeo Pocket Color       31
N-Gage                    30
Game Boy                  22
iPod                      17
Sega 32X                  16
Windows Phone             14
Master System             13
Arcade                    11
NeoGeo                    10
Linux                     10
Nintendo 64DD              7
Commodore 64/128           6
Saturn                     6
Atari 2600                 5
WonderSwan                 4
TurboGrafx-CD              3
Game.Com                   3
New Nintendo 3DS           2
Atari 5200                 2
Vectrex                    2
WonderSwan Color           1
Web Games                  1
Dreamcast VMU              1
Ouya                       1
DVD / HD Video Game        1
SteamOS                    1
Pocket PC                  1
Windows Surface            1
Sega CD                    1
Name: Platform, dtype: int64

In [16]:
salesdec.Platform.value_counts()

PS2     2161
DS      2152
PS3     1331
Wii     1320
X360    1262
PSP     1209
PS      1197
PC       974
XB       824
GBA      822
GC       556
3DS      520
PSV      432
PS4      393
N64      319
XOne     247
SNES     239
SAT      173
WiiU     147
2600     133
GB        98
NES       98
DC        52
GEN       29
NG        12
WS         6
SCD        6
3DO        3
TG16       2
PCFX       1
GG         1
Name: Platform, dtype: int64

In [17]:
plat = pd.read_csv('Platform_Title.csv', delimiter=',') #created csv that took both platform columns from both dataframes
plat = dict(zip(plat.Full_Name, plat.Abbreviation))

#created a dict to standardize the platform names
ign['Standard_Plat'] = ign['Platform'].map(plat)
ign[['Platform','Standard_Plat']].head()

           Platform Standard_Plat
0  PlayStation Vita           PSV
1  PlayStation Vita           PSV
2              iPad           NaN
3          Xbox 360          X360
4     PlayStation 3           PS3

In [18]:
salesdec['Standard_Plat'] = salesdec['Platform']
del salesdec['Platform']

In [19]:
df = pd.merge(ign, salesdec, on=['Name','Standard_Plat'], how='inner',indicator=True) #merge both upon standardization

In [20]:
gta = df[df.Name =='Grand Theft Auto V']
gta[['Platform','Standard_Plat','Name','Global_Sales','Critic_Score','Release_Date','Year_of_Release','_merge']]

,Platform,Standard_Plat,Name,Global_Sales,Critic_Score,Release_Date,Year_of_Release,_merge
7013,PlayStation 3,PS3,Grand Theft Auto V,21.04,97.0,2013-09-16,2013.0,both
7014,Xbox 360,X360,Grand Theft Auto V,16.27,97.0,2013-09-16,2013.0,both
7309,PlayStation 4,PS4,Grand Theft Auto V,12.61,97.0,2014-11-17,2014.0,both
7310,Xbox One,XOne,Grand Theft Auto V,5.48,97.0,2014-11-17,2014.0,both
7328,PC,PC,Grand Theft Auto V,1.17,96.0,2015-04-14,2015.0,both

In [21]:
#checking if there are any that don't match fully
df['_merge'].value_counts()

both          7501
right_only       0
left_only        0
Name: _merge, dtype: int64

In [22]:
df[df.genre.isnull()]

,score_phrase,Name,url,Platform,score,genre,editors_choice,release_year,release_month,release_day,...,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,_merge
5347,Bad,PopStar Guitar,/games/popstar-guitar/ps2-14268729,PlayStation 2,4.0,NaN,N,2008,12,18,...,0.00,0.00,0.04,NaN,NaN,tbd,NaN,XS Games,T,both
6497,Good,Naruto Shippuden: Kizuna Drive,/games/naruto-shippuden-kizuna-drive/psp-65765,PlayStation Portable,7.0,NaN,N,2011,3,24,...,0.05,0.01,0.13,57.0,22.0,5,6.0,Premium Agency,T,both

In [23]:
df[['Genre','genre']]

             Genre               genre
0         Platform          Platformer
1           Sports              Sports
2           Sports              Sports
3           Action                 RPG
4         Fighting            Fighting
5         Fighting            Fighting
6           Action   Action, Adventure
7     Role-Playing         Action, RPG
8     Role-Playing                 RPG
9          Shooter   Action, Adventure
10         Shooter   Action, Adventure
11          Sports              Sports
12          Sports              Sports
13          Sports              Sports
14          Sports              Sports
15          Sports              Sports
16          Sports              Sports
17          Sports              Sports
18        Fighting            Fighting
19        Fighting            Fighting
20       Adventure           Adventure
21          Action             Shooter
22          Action             Shooter
23          Action              Action
24          Racing              Racing
25          Action              Sports
26    Role-Playing       Strategy, RPG
27    Role-Playing         Action, RPG
28          Action              Puzzle
29          Action   Action, Adventure
...            ...                 ...
7471       Shooter             Shooter
7472       Shooter   Action, Adventure
7473  Role-Playing         Action, RPG
7474      Strategy            Strategy
7475      Platform  Action, Platformer
7476      Platform   Action, Adventure
7477      Platform   Action, Adventure
7478      Platform   Action, Adventure
7479        Action   Action, Adventure
7480  Role-Playing                 RPG
7481       Shooter             Shooter
7482       Shooter             Shooter
7483       Shooter             Shooter
7484       Shooter             Shooter
7485      Strategy            Strategy
7486      Fighting            Fighting
7487      Fighting            Fighting
7488       Shooter             Shooter
7489       Shooter             Shooter
7490       Shooter             Shooter
7491        Action          Platformer
7492  Role-Playing         Action, RPG
7493  Role-Playing         Action, RPG
7494  Role-Playing         Action, RPG
7495        Action             Shooter
7496        Action  Shooter, Adventure
7497        Sports              Sports
7498        Action           Adventure
7499        Action      Racing, Action
7500        Action           Adventure

[7501 rows x 2 columns]

In [24]:
df.iloc[7:11][['Genre','genre','Name','Release_Date','_merge','Standard_Plat','Platform','Year_of_Release']]

,Genre,genre,Name,Release_Date,_merge,Standard_Plat,Platform,Year_of_Release
7,Role-Playing,"Action, RPG",Legasista,2012-08-28,both,PS3,PlayStation 3,2012.0
8,Role-Playing,RPG,World of Warcraft: Mists of Pandaria,2012-10-04,both,PC,PC,2012.0
9,Shooter,"Action, Adventure",Resident Evil 6,2012-10-01,both,PS3,PlayStation 3,2012.0
10,Shooter,"Action, Adventure",Resident Evil 6,2012-10-01,both,X360,Xbox 360,2012.0

In [43]:
g = df[(df.genre.isin(df.Genre)==False)]
g[['genre','Genre','Name','_merge','Platform','Standard_Plat']].head()

,genre,Genre,Name,_merge,Platform,Standard_Plat
0,Platformer,Platform,LittleBigPlanet PS Vita,both,PlayStation Vita,PSV
3,RPG,Action,Guild Wars 2,both,PC,PC
6,"Action, Adventure",Action,Way of the Samurai 4,both,PlayStation 3,PS3
7,"Action, RPG",Role-Playing,Legasista,both,PlayStation 3,PS3
8,RPG,Role-Playing,World of Warcraft: Mists of Pandaria,both,PC,PC

In [39]:
len(df.genre.value_counts())

81

In [40]:
len(df.Genre.value_counts())

12

In [44]:
df.Genre.value_counts() #GENRE!!!

Action          1559
Sports          1222
Shooter          887
Racing           684
Role-Playing     629
Platform         501
Misc             490
Fighting         389
Simulation       339
Strategy         296
Adventure        269
Puzzle           236
Name: Genre, dtype: int64

In [47]:
#delete 'genre' column

In [48]:
del df['genre']

In [58]:
df.to_csv('cleaned_vg_df')