## Capstone Project: Video Game Ratings and Sales

There are two sets of video game data, both of which are obtained from Kaggle. One dataset contains the title, platform, score, release date, score, and whether it's an editor's choice. This dataset was already scraped from IGN.com upon downloading it from Kaggle. The second dataset has similar observations with the first one, but also contains sales information. I wanted to combine both datasets together since the only difference in information is with the sales and the ratings (pulled from different resources). 

source:

dataset1: https://www.kaggle.com/egrinstein/20-years-of-games

dataset2: https://www.kaggle.com/rush4ratio/video-game-sales-with-ratings

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
from __future__ import division
import math
from datetime import datetime

### Dataset #1 from IGN

The first dataset contained a column 'Unnamed:0' that has no valuable information and acted as an index. This column was deleted. There are also three separate columns for the release year, month and day respectively. These columns were combined into a single column with its values as a datetime object.

In [39]:
ign = pd.read_csv ("ign.csv")

ign = ign.drop('Unnamed: 0', axis=1)

ign.head()

,score_phrase,title,url,platform,score,genre,editors_choice,release_year,release_month,release_day
0,Amazing,LittleBigPlanet PS Vita,/games/littlebigplanet-vita/vita-98907,PlayStation Vita,9.0,Platformer,Y,2012,9,12
1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,/games/littlebigplanet-ps-vita-marvel-super-he...,PlayStation Vita,9.0,Platformer,Y,2012,9,12
2,Great,Splice: Tree of Life,/games/splice/ipad-141070,iPad,8.5,Puzzle,N,2012,9,12
3,Great,NHL 13,/games/nhl-13/xbox-360-128182,Xbox 360,8.5,Sports,N,2012,9,11
4,Great,NHL 13,/games/nhl-13/ps3-128181,PlayStation 3,8.5,Sports,N,2012,9,11

### Dataset #2 from vg

The only thing to note about this dataset

In [40]:
salesdec = pd.read_csv ("Video_Games_Sales_as_at_22_Dec_2016.csv")
salesdec.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

### Standardizing the Column Label Format for Merging

Both of the DataFrames have similar columns, but with different labels. So to standardized the column labels the first dataframe's column labels used for merging is changed to match the second dataframe's format label.

In [41]:
ign = ign.rename(columns={'title':'Name', 'platform':'Platform'})
#ign.rename(columns={'platform':'Platform'}, inplace=True)

In [42]:
#s1 = pd.merge(ign, salesdec, left_on=['genre','platform'], right_on=['Genre','Platform'])

In [43]:
#s1[['Genre','genre']]

In [7]:
ign.head()

,score_phrase,Name,url,Platform,score,genre,editors_choice,release_year,release_month,release_day
0,Amazing,LittleBigPlanet PS Vita,/games/littlebigplanet-vita/vita-98907,PlayStation Vita,9.0,Platformer,Y,2012,9,12
1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,/games/littlebigplanet-ps-vita-marvel-super-he...,PlayStation Vita,9.0,Platformer,Y,2012,9,12
2,Great,Splice: Tree of Life,/games/splice/ipad-141070,iPad,8.5,Puzzle,N,2012,9,12
3,Great,NHL 13,/games/nhl-13/xbox-360-128182,Xbox 360,8.5,Sports,N,2012,9,11
4,Great,NHL 13,/games/nhl-13/ps3-128181,PlayStation 3,8.5,Sports,N,2012,9,11

In [44]:
salesdec.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#df['period'] = df[['Year', 'quarter']].apply(lambda x: ''.join(x), axis=1)
#dataframe["period"] = dataframe["Year"].map(str) + dataframe["quarter"]
#datetime.datetime.strptime(string_date, "%Y-%m-%d %H:%M:%S.%f")

In [45]:
ign['Release_Date'] = ign['release_year'].map(str) +'-' + ign['release_month'].map(str) + '-' +ign['release_day'].map(str)

ign['Release_Date'] = pd.to_datetime(ign['Release_Date']) #creating new column with timeseries oh YEAR:MONTH:DATE

In [46]:
ign.head()

,score_phrase,Name,url,Platform,score,genre,editors_choice,release_year,release_month,release_day,Release_Date
0,Amazing,LittleBigPlanet PS Vita,/games/littlebigplanet-vita/vita-98907,PlayStation Vita,9.0,Platformer,Y,2012,9,12,2012-09-12
1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,/games/littlebigplanet-ps-vita-marvel-super-he...,PlayStation Vita,9.0,Platformer,Y,2012,9,12,2012-09-12
2,Great,Splice: Tree of Life,/games/splice/ipad-141070,iPad,8.5,Puzzle,N,2012,9,12,2012-09-12
3,Great,NHL 13,/games/nhl-13/xbox-360-128182,Xbox 360,8.5,Sports,N,2012,9,11,2012-09-11
4,Great,NHL 13,/games/nhl-13/ps3-128181,PlayStation 3,8.5,Sports,N,2012,9,11,2012-09-11

### The two dataframes are then merged on by the Name and Platform columns

In [12]:
x = pd.merge(ign, salesdec, on=['Name','Platform'], suffixes=['_ign','_vg'], how='outer', indicator=True)
x.head()

,score_phrase,Name,url,Platform,score,genre,editors_choice,release_year,release_month,release_day,...,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,_merge
0,Amazing,LittleBigPlanet PS Vita,/games/littlebigplanet-vita/vita-98907,PlayStation Vita,9.0,Platformer,Y,2012.0,9.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,/games/littlebigplanet-ps-vita-marvel-super-he...,PlayStation Vita,9.0,Platformer,Y,2012.0,9.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,Great,Splice: Tree of Life,/games/splice/ipad-141070,iPad,8.5,Puzzle,N,2012.0,9.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,Great,NHL 13,/games/nhl-13/xbox-360-128182,Xbox 360,8.5,Sports,N,2012.0,9.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,Great,NHL 13,/games/nhl-13/ps3-128181,PlayStation 3,8.5,Sports,N,2012.0,9.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [52]:
b = x[x.Name == 'Grand Theft Auto V']
b[['Name', 'Platform','Global_Sales','_merge']]

                     Name       Platform  Global_Sales      _merge
17163  Grand Theft Auto V  PlayStation 3           NaN   left_only
17164  Grand Theft Auto V       Xbox 360           NaN   left_only
17998  Grand Theft Auto V  PlayStation 4           NaN   left_only
17999  Grand Theft Auto V       Xbox One           NaN   left_only
18067  Grand Theft Auto V             PC          1.17        both
18635  Grand Theft Auto V            PS3         21.04  right_only
18642  Grand Theft Auto V           X360         16.27  right_only
18660  Grand Theft Auto V            PS4         12.61  right_only
18770  Grand Theft Auto V           XOne          5.48  right_only

### Standardizing the Platform Column
Upon checking to see if the merge is successful, it seems that the Platform column values from both dataframes have different values such that Playstation 3 is labeled as PS3 in the other dataframe. To fix this, a value count as taken from both dataframes to list all the uniqu platforms in both dataframes. This was then copied and pasted into an excel sheet to match the corresponding abbreviations to the full platform name. The excel sheet was then loaded as a dictionary and mapped to the Platform column in the merged dataframe

In [14]:
#checking for all possible values for platform names

In [48]:
ign['Platform'].value_counts()

PC                      3370
PlayStation 2           1686
Xbox 360                1631
Wii                     1366
PlayStation 3           1356
Nintendo DS             1045
PlayStation              952
Wireless                 910
iPhone                   842
Xbox                     821
PlayStation Portable     633
Game Boy Advance         623
GameCube                 509
Game Boy Color           356
Nintendo 64              302
Dreamcast                286
PlayStation 4            277
Nintendo DSi             254
Nintendo 3DS             225
Xbox One                 208
PlayStation Vita         155
Wii U                    114
iPad                      99
Lynx                      82
Macintosh                 81
Genesis                   58
NES                       49
TurboGrafx-16             40
Android                   39
Super NES                 33
NeoGeo Pocket Color       31
N-Gage                    30
Game Boy                  22
iPod                      17
Sega 32X                  16
Windows Phone             14
Master System             13
Arcade                    11
NeoGeo                    10
Linux                     10
Nintendo 64DD              7
Commodore 64/128           6
Saturn                     6
Atari 2600                 5
WonderSwan                 4
TurboGrafx-CD              3
Game.Com                   3
New Nintendo 3DS           2
Atari 5200                 2
Vectrex                    2
WonderSwan Color           1
Web Games                  1
Dreamcast VMU              1
Ouya                       1
DVD / HD Video Game        1
SteamOS                    1
Pocket PC                  1
Windows Surface            1
Sega CD                    1
Name: Platform, dtype: int64

In [49]:
salesdec.Platform.value_counts()

PS2     2161
DS      2152
PS3     1331
Wii     1320
X360    1262
PSP     1209
PS      1197
PC       974
XB       824
GBA      822
GC       556
3DS      520
PSV      432
PS4      393
N64      319
XOne     247
SNES     239
SAT      173
WiiU     147
2600     133
GB        98
NES       98
DC        52
GEN       29
NG        12
WS         6
SCD        6
3DO        3
TG16       2
PCFX       1
GG         1
Name: Platform, dtype: int64

In [98]:
plat = pd.read_csv('Platform_Title.csv', delimiter=',') #created csv that took both platform columns from both dataframes
plat = dict(zip(plat.Full_Name, plat.Abbreviation))
plat

#created a dict to standardize the platform names
ign['Standard_Plat'] = ign['Platform'].map(plat)

In [99]:
plat

{'Android': nan,
 'Arcade': nan,
 'Atari 2600': '2600',
 'Atari 5200': nan,
 'Commodore 64/128': nan,
 'DVD / HD Video Game': nan,
 'Dreamcast': 'DC',
 'Dreamcast VMU': nan,
 'Game Boy': 'GB',
 'Game Boy Advance': 'GBA',
 'Game Boy Color': nan,
 'Game.Com': nan,
 'GameCube': 'GC',
 'Genesis': 'GEN',
 'Linux': nan,
 'Lynx': nan,
 'Macintosh': nan,
 'Master System': nan,
 'N-Gage': nan,
 'NES': 'NES',
 'NeoGeo': 'NG',
 'NeoGeo Pocket Color': nan,
 'New Nintendo 3DS': nan,
 'Nintendo 3DS': '3DS',
 'Nintendo 64': 'N64',
 'Nintendo 64DD': nan,
 'Nintendo DS': 'DS',
 'Nintendo Dsi': nan,
 'Ouya': nan,
 'PC': 'PC',
 'PlayStation': 'PS',
 'PlayStation 2': 'PS2',
 'PlayStation 3': 'PS3',
 'PlayStation 4': 'PS4',
 'PlayStation Portable': 'PSP',
 'PlayStation Vita': 'PSV',
 'Pocket PC': nan,
 'Saturn': 'SAT',
 'Sega 32X': nan,
 'Sega CD': 'SCD',
 'SteamOS': nan,
 'Super NES': 'SNES',
 'TurboGrafx-16': 'TG16',
 'TurboGrafx-CD': nan,
 'Vectrex': nan,
 'Web Games': nan,
 'Wii': 'Wii',
 'Wii U': 'WiiU',
 'Windows Phone': nan,
 'Windows Surface': nan,
 'Wireless': nan,
 'WonderSwan': 'WS',
 'WonderSwan Color': nan,
 'Xbox': 'XB',
 'Xbox 360': 'X360',
 'Xbox One': 'XOne',
 'iPad': nan,
 'iPhone': nan,
 'iPod': nan}

In [77]:
salesdec['Standard_Plat'] = salesdec['Platform']
salesdec['Standard_Plat'].isnull().any()
#del salesdec['Platform']

False

### Merging the Two DataFrames after Standardization of Column Labels and Cleaning

In [95]:
df = pd.merge(ign, salesdec, on=['Name','Standard_Plat'], how='outer',indicator=True) #merge both upon standardization
df.isnull().any()

score_phrase        True
Name                True
url                 True
Platform_x          True
score               True
genre               True
editors_choice      True
release_year        True
release_month       True
release_day         True
Release_Date        True
Standard_Plat       True
Platform_y          True
Year_of_Release     True
Genre               True
Publisher           True
NA_Sales            True
EU_Sales            True
JP_Sales            True
Other_Sales         True
Global_Sales        True
Critic_Score        True
Critic_Count        True
User_Score          True
User_Count          True
Developer           True
Rating              True
_merge             False
dtype: bool

In [96]:
df[['Name','Standard_Plat','Platform_x','Platform_y']]

,Name,Standard_Plat,Platform_x,Platform_y
0,LittleBigPlanet PS Vita,PSV,PlayStation Vita,PSV
1,LittleBigPlanet PS Vita -- Marvel Super Hero E...,PSV,PlayStation Vita,NaN
2,Splice: Tree of Life,NaN,iPad,NaN
3,NHL 13,X360,Xbox 360,X360
4,NHL 13,PS3,PlayStation 3,PS3
5,Total War Battles: Shogun,NaN,Macintosh,NaN
6,Double Dragon: Neon,X360,Xbox 360,NaN
7,Guild Wars 2,PC,PC,PC
8,Double Dragon: Neon,PS3,PlayStation 3,NaN
9,Total War Battles: Shogun,PC,PC,NaN
10,Tekken Tag Tournament 2,PS3,PlayStation 3,PS3
11,Tekken Tag Tournament 2,X360,Xbox 360,X360
12,Wild Blood,NaN,iPhone,NaN
13,Mark of the Ninja,X360,Xbox 360,NaN
14,Mark of the Ninja,PC,PC,NaN
15,Home: A Unique Horror Adventure,NaN,Macintosh,NaN
16,Home: A Unique Horror Adventure,PC,PC,NaN
17,Avengers Initiative,NaN,iPhone,NaN
18,Way of the Samurai 4,PS3,PlayStation 3,PS3
19,JoJo's Bizarre Adventure HD,X360,Xbox 360,NaN
20,JoJo's Bizarre Adventure HD,PS3,PlayStation 3,NaN
21,Mass Effect 3: Leviathan,X360,Xbox 360,NaN
22,Mass Effect 3: Leviathan,PS3,PlayStation 3,NaN
23,Mass Effect 3: Leviathan,PC,PC,NaN
24,Dark Souls (Prepare to Die Edition),PC,PC,NaN
25,Symphony,PC,PC,NaN
26,Bastion,NaN,iPad,NaN
27,Tom Clancy's Ghost Recon Phantoms,PC,PC,NaN
28,Thirty Flights of Loving,PC,PC,NaN
29,Legasista,PS3,PlayStation 3,PS3
...,...,...,...,...
27840,XI Coliseum,PSP,NaN,PSP
27841,Kyoukai no Shirayuki,PSV,NaN,PSV
27842,Worms 2,PC,NaN,PC
27843,Grisaia no Kajitsu: La Fruit de la Grisaia,PSP,NaN,PSP
27844,Scarlett: Nichijou no Kyoukaisen,PS2,NaN,PS2
27845,7'scarlet,PSV,NaN,PSV
27846,Help Wanted: 50 Wacky Jobs (jp sales),Wii,NaN,Wii
27847,Yattaman Wii: BikkuriDokkiri Machine de Mou Ra...,Wii,NaN,Wii
27848,Neo Angelique Special,PSP,NaN,PSP
27849,Outdoors Unleashed: Africa 3D,3DS,NaN,3DS
27850,Real Rode,PS2,NaN,PS2
27851,Pony Friends 2,PC,NaN,PC
27852,Dynasty Warriors: Eiketsuden,PS3,NaN,PS3
27853,Planet Monsters,GBA,NaN,GBA
27854,Bust-A-Move 3000,GC,NaN,GC
27855,The Longest 5 Minutes,PSV,NaN,PSV
27856,Mezase!! Tsuri Master DS,DS,NaN,DS
27857,Eiyuu Densetsu: Sora no Kiseki Material Collec...,PSP,NaN,PSP
27858,STORM: Frontline Nation,PC,NaN,PC
27859,Strawberry Nauts,PSV,NaN,PSV
27860,15 Days,PC,NaN,PC
27861,Men in Black II: Alien Escape,GC,NaN,GC
27862,Aiyoku no Eustia,PSV,NaN,PSV
27863,Woody Woodpecker in Crazy Castle 5,GBA,NaN,GBA
27864,SCORE International Baja 1000: The Official Game,PS2,NaN,PS2
27865,Samurai Warriors: Sanada Maru,PS3,NaN,PS3
27866,LMA Manager 2007,X360,NaN,X360
27867,Haitaka no Psychedelica,PSV,NaN,PSV
27868,Spirits & Spells,GBA,NaN,GBA
27869,Winning Post 8 2016,PSV,NaN,PSV

In [88]:
df.Standard_Plat.value_counts()

PS2     1182
X360     752
DS       741
PS3      664
XB       622
PS       596
Wii      563
PC       542
GC       396
PSP      395
GBA      353
N64      209
PS4      109
XOne      92
3DS       92
WiiU      58
PSV       53
DC        24
NES       22
SNES      13
GB         8
GEN        6
SAT        5
2600       3
NG         1
Name: Standard_Plat, dtype: int64

In [21]:
gta = df[df.Name =='Grand Theft Auto V']
gta[['Platform','Standard_Plat','Name','Global_Sales','Critic_Score','Release_Date','Year_of_Release','_merge']]

,Platform,Standard_Plat,Name,Global_Sales,Critic_Score,Release_Date,Year_of_Release,_merge
7013,PlayStation 3,PS3,Grand Theft Auto V,21.04,97.0,2013-09-16,2013.0,both
7014,Xbox 360,X360,Grand Theft Auto V,16.27,97.0,2013-09-16,2013.0,both
7309,PlayStation 4,PS4,Grand Theft Auto V,12.61,97.0,2014-11-17,2014.0,both
7310,Xbox One,XOne,Grand Theft Auto V,5.48,97.0,2014-11-17,2014.0,both
7328,PC,PC,Grand Theft Auto V,1.17,96.0,2015-04-14,2015.0,both

In [22]:
#checking if there are any that don't match fully
df['_merge'].value_counts()

both          7501
right_only       0
left_only        0
Name: _merge, dtype: int64

In [23]:
df[df.genre.isnull()]

,score_phrase,Name,url,Platform,score,genre,editors_choice,release_year,release_month,release_day,...,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,_merge
5347,Bad,PopStar Guitar,/games/popstar-guitar/ps2-14268729,PlayStation 2,4.0,NaN,N,2008,12,18,...,0.00,0.00,0.04,NaN,NaN,tbd,NaN,XS Games,T,both
6497,Good,Naruto Shippuden: Kizuna Drive,/games/naruto-shippuden-kizuna-drive/psp-65765,PlayStation Portable,7.0,NaN,N,2011,3,24,...,0.05,0.01,0.13,57.0,22.0,5,6.0,Premium Agency,T,both

## Genre Column not standardized

Upon the merge, the genre column(s) from both dataframes are not standardized either. A value counts was done to check the numbe of unique values for genres in general. Since there are many mutli genres such as Action, Adventure or Shooting, Adventure, the latter genre column was used instead because it only contained 12 unique genres. The other genre column as then deleted.

In [24]:
df[['Genre','genre']]

             Genre               genre
0         Platform          Platformer
1           Sports              Sports
2           Sports              Sports
3           Action                 RPG
4         Fighting            Fighting
5         Fighting            Fighting
6           Action   Action, Adventure
7     Role-Playing         Action, RPG
8     Role-Playing                 RPG
9          Shooter   Action, Adventure
10         Shooter   Action, Adventure
11          Sports              Sports
12          Sports              Sports
13          Sports              Sports
14          Sports              Sports
15          Sports              Sports
16          Sports              Sports
17          Sports              Sports
18        Fighting            Fighting
19        Fighting            Fighting
20       Adventure           Adventure
21          Action             Shooter
22          Action             Shooter
23          Action              Action
24          Racing              Racing
25          Action              Sports
26    Role-Playing       Strategy, RPG
27    Role-Playing         Action, RPG
28          Action              Puzzle
29          Action   Action, Adventure
...            ...                 ...
7471       Shooter             Shooter
7472       Shooter   Action, Adventure
7473  Role-Playing         Action, RPG
7474      Strategy            Strategy
7475      Platform  Action, Platformer
7476      Platform   Action, Adventure
7477      Platform   Action, Adventure
7478      Platform   Action, Adventure
7479        Action   Action, Adventure
7480  Role-Playing                 RPG
7481       Shooter             Shooter
7482       Shooter             Shooter
7483       Shooter             Shooter
7484       Shooter             Shooter
7485      Strategy            Strategy
7486      Fighting            Fighting
7487      Fighting            Fighting
7488       Shooter             Shooter
7489       Shooter             Shooter
7490       Shooter             Shooter
7491        Action          Platformer
7492  Role-Playing         Action, RPG
7493  Role-Playing         Action, RPG
7494  Role-Playing         Action, RPG
7495        Action             Shooter
7496        Action  Shooter, Adventure
7497        Sports              Sports
7498        Action           Adventure
7499        Action      Racing, Action
7500        Action           Adventure

[7501 rows x 2 columns]

In [25]:
df.iloc[7:11][['Genre','genre','Name','Release_Date','_merge','Standard_Plat','Platform','Year_of_Release']]

,Genre,genre,Name,Release_Date,_merge,Standard_Plat,Platform,Year_of_Release
7,Role-Playing,"Action, RPG",Legasista,2012-08-28,both,PS3,PlayStation 3,2012.0
8,Role-Playing,RPG,World of Warcraft: Mists of Pandaria,2012-10-04,both,PC,PC,2012.0
9,Shooter,"Action, Adventure",Resident Evil 6,2012-10-01,both,PS3,PlayStation 3,2012.0
10,Shooter,"Action, Adventure",Resident Evil 6,2012-10-01,both,X360,Xbox 360,2012.0

In [26]:
g = df[(df.genre.isin(df.Genre)==False)]
g[['genre','Genre','Name','_merge','Platform','Standard_Plat']].head()

,genre,Genre,Name,_merge,Platform,Standard_Plat
0,Platformer,Platform,LittleBigPlanet PS Vita,both,PlayStation Vita,PSV
3,RPG,Action,Guild Wars 2,both,PC,PC
6,"Action, Adventure",Action,Way of the Samurai 4,both,PlayStation 3,PS3
7,"Action, RPG",Role-Playing,Legasista,both,PlayStation 3,PS3
8,RPG,Role-Playing,World of Warcraft: Mists of Pandaria,both,PC,PC

In [27]:
len(df.genre.value_counts())

81

In [28]:
len(df.Genre.value_counts())

12

In [29]:
df.Genre.value_counts() #GENRE!!!

Action          1559
Sports          1222
Shooter          887
Racing           684
Role-Playing     629
Platform         501
Misc             490
Fighting         389
Simulation       339
Strategy         296
Adventure        269
Puzzle           236
Name: Genre, dtype: int64

In [30]:
#delete 'genre' column

In [31]:
del df['genre']

### Checking if the Release Years are the same from Both Datasets

There are some observations that don't have matching release years from both datasets. But since one of the release year columns are associated with a dataset that contains matching global sales, both of the release year columns are then kept. However, the one associated with global sales is renamed to Year_of_Release_Sales to clear any confusion for future analysis.

In [32]:
poo = df[df.Year_of_Release.isin(df.release_year)==False]
poo[['Year_of_Release','release_year', 'Name','Platform']].head()

     Year_of_Release  release_year                Name     Platform
122           1995.0          1996            Robo Pit  PlayStation
123           1995.0          1996        NBA ShootOut  PlayStation
124           1995.0          1996   Beyond The Beyond  PlayStation
126           1995.0          1996                   D  PlayStation
128           1994.0          1996  ESPN Extreme Games  PlayStation

In [33]:
df.rename(columns={'Year_of_Release':'Year_of_Release_Sales'}, inplace=True)

### Missing Data 

The majority of the missing data are in columns associatd with Ratings. These missing values are going to be kept as is.

In [34]:
df.isnull().any()

score_phrase             False
Name                     False
url                      False
Platform                 False
score                    False
editors_choice           False
release_year             False
release_month            False
release_day              False
Release_Date             False
Standard_Plat            False
Year_of_Release_Sales     True
Genre                    False
Publisher                 True
NA_Sales                 False
EU_Sales                 False
JP_Sales                 False
Other_Sales              False
Global_Sales             False
Critic_Score              True
Critic_Count              True
User_Score                True
User_Count                True
Developer                 True
Rating                    True
_merge                   False
dtype: bool

### Outliers

Outliers are kept in the dataset for now. The outliers calculated were for the global sales in millions.

In [35]:
def zscore(series):
    #calculating the z-score where z=(x-mean)/std
    return (series-series.mean())/series.std()

In [36]:
gs = df['Global_Sales'] * 1000000
zz = zscore(gs)
zz[zz>3]

31       4.007587
63       4.844826
69       3.083922
75       6.983837
76       7.048656
125      3.283780
194      6.022363
200      4.931251
263      3.969776
290      3.694297
322      4.850227
443      3.467432
470      3.705100
573      3.845540
699      4.725992
1132     6.675949
1147     3.073119
1183     3.418818
1226     3.948170
1349     3.289181
1440     3.008301
1491     3.056915
1604     8.323420
2159     3.354000
2210     3.489038
2661     4.185838
2676     3.326992
2688    10.840540
2783     5.898127
3139     3.753714
          ...
6280     4.925849
6309     4.126421
6331     5.379579
6365     7.491583
6366     6.422077
6382     3.078521
6694     5.066289
6730     3.553857
6739     3.472834
6742     3.240567
6748     7.556401
6755     6.794783
6762     3.062316
6774     4.347884
6777     6.438281
6782     5.438996
6896     4.558544
6917     4.947455
7003     4.547741
7013    10.964776
7014     8.388239
7056     3.094726
7074     4.655772
7075     5.136509
7228     3.429621
7280     3.737509
7309     6.411274
7370     3.467432
7407     4.229050
7447     3.699699
Name: Global_Sales, dtype: float64

In [37]:
df.to_csv('cleaned_vg_df')

In [38]:
df.shape

(7501, 26)